plugins {
    id 'java'
    id 'java-gradle-plugin'
    id 'maven-publish'
    id 'net.linguica.maven-settings' version '0.5'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(java_version)
    }
    sourceCompatibility = JavaLanguageVersion.of(java_version)
    targetCompatibility = JavaLanguageVersion.of(java_version)
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
}

base {
    archivesName = name
}
group = group
version = plugin_version

gradlePlugin {
    plugins {
        register('modupdate') {
            id = 'mod-update'
            displayName = 'mod-update'
            implementationClass = 'de.maxhenkel.modupdate.UpdatePlugin'
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation gradleApi()
    implementation "com.konghq:unirest-java-core:${unirest_version}"
    implementation "com.konghq:unirest-object-mappers-gson:${unirest_gson_version}"
}

tasks.register('javadocJar', Jar) {
    classifier 'javadoc'
    from javadoc
}

tasks.register('sourcesJar', Jar) {
    from sourceSets.main.allSource
    classifier 'sources'
}

jar {
    manifest {
        attributes 'Implementation-Version': archiveVersion
    }
}

publishing {
    publications {
        modUpdate(MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            name = 'henkelmax.public'
            url = 'https://maven.maxhenkel.de/repository/public'
        }
    }
}